run:
  timeout: 5m

linters-settings:
  errcheck:
    exclude-functions:
      - "(*github.com/mgr9525/HyperByte-Transfer-Protocol.Context).ResString"
      - "(*github.com/mgr9525/HyperByte-Transfer-Protocol.Context).ResJson"
